import yaml
import numpy as np
from dataclasses import dataclass

@dataclass
class FabricsArgumentSize():
    GOAL_WEIGTH_DIM : int = 1
    OBSTACLE_DIM : int = 1
    OBSTACLE_POS_DIM : int = 3
    COLLISION_LINK_DIM : int = 1
    PLANE_CONSTRAINT_DIM : int = 4


class FabricsConfig():
    def __init__(self, config_file = None) -> None:
        if config_file is None:
            raise RuntimeError("No config file for fabrics loaded.")
        self.config = self.read_config_file(config_file)
        self.input_args_fabrics = self._init_input_fabrics()
        self._n_dof = self.config["num_dofs"]
        self.print_input_args()

    def read_config_file(self, config_file) -> dict:
        """
        Read all data necessary for determining the arguments for the autogenerated fabrics function
        """
        with open(config_file, 'r') as config_file:
            config = yaml.safe_load(config_file)
        
        fabrics_config = {}
        fabrics_config["dim_states"] = 2
        fabrics_config["num_obstacles"] = config["problem"]["environment"]["number_spheres"]["dynamic"] \
                                         + config["problem"]["environment"]["number_spheres"]["static"]
        fabrics_config["num_collision_link"] = len(config["problem"]["robot_representation"]["collision_links"])
        fabrics_config["num_planes"]  = config["problem"]["environment"]["number_planes"]
        fabrics_config["num_dofs"]  = len(config["problem"]["joint_limits"]["lower_limits"])
        fabrics_config["dim_goals"] = self.handle_goals(config)
        
        return fabrics_config
    
    def handle_goals(self, config) -> dict:
        goals = {}
        for name, subgoal in config["problem"]["goal"]["goal_definition"].items():
            goals[name] = len(subgoal["indices"])
        return goals
    
    def get_fabrics_config(self) -> dict:
        return self.config

    def _init_input_fabrics(self) -> dict:
        self.desired_msg_types = 0
        input_args = {}
        # plane constraint
        for i in range(self.config["num_planes"]):
            input_args["plane_g_"+ str(i)] = np.zeros((FabricsArgumentSize.PLANE_CONSTRAINT_DIM), dtype=np.float64)
            self.desired_msg_types += 1
        # Robot state (q, qdot)
        for i in range(2):
            input_args["q_state_" + str(i)] = np.zeros((self.config["num_dofs"]), dtype=np.float64)
            self.desired_msg_types += 1
        # radius body
        for i in range(self.config["num_collision_link"]):
            input_args["radius_body_"+str(i)] = np.zeros((FabricsArgumentSize.COLLISION_LINK_DIM), dtype=np.float64)
            self.desired_msg_types += 1
        # radius obstacle
        for i in range(self.config["num_obstacles"]):
            input_args["radius_obst_"+str(i)] = np.zeros((FabricsArgumentSize.OBSTACLE_DIM), dtype=np.float64)
            self.desired_msg_types += 1
        # weight goal
        for i in range(len(self.config["dim_goals"])):
            input_args["weight_goal_"+str(i)] = np.zeros((FabricsArgumentSize.GOAL_WEIGTH_DIM), dtype=np.float64)
            self.desired_msg_types += 1
        # goals
        for i, (_, length) in enumerate(self.config["dim_goals"].items()):
            input_args["x_goal_"+str(i)] = np.zeros((length), dtype=np.float64)
            self.desired_msg_types += 1
        # obstacle pos
        for i in range(self.config["num_obstacles"]):
            input_args["x_obst_"+str(i)] = np.zeros((FabricsArgumentSize.OBSTACLE_POS_DIM), dtype=np.float64)
            self.desired_msg_types += 1
        return input_args


    def print_input_args(self):
        print("Fabrics input args\n---")
        for keys, values in self.input_args_fabrics.items():
            print(f"{keys}: {values}")
        print("---")

    def handle_input_arg_dict(self, arg_dict:dict) -> list:
        msg_type_counter = 0
        # Plane constraint
        if self.config["num_planes"] > 0:
            plane_constraints = [k for k, v in arg_dict.items() if k.startswith('constraint_')]
            for i, plane_g in enumerate(plane_constraints):
                # data.append(np.asarray(arg_dict[plane_g]))
                self.input_args_fabrics["plane_g_"+ str(i)][:FabricsArgumentSize.PLANE_CONSTRAINT_DIM] = np.asarray(arg_dict[plane_g], dtype=np.float64)
            msg_type_counter += 1

        # robot state
        self.input_args_fabrics["q_state_0"][:self._n_dof] = np.asarray(arg_dict["q"], dtype=np.float64)
        self.input_args_fabrics["q_state_1"][:self._n_dof] = np.asarray(arg_dict["qdot"], dtype=np.float64)

        msg_type_counter += 2

        # radius body
        if self.config["num_collision_link"] > 0:
            radius_body = [v for k, v in arg_dict.items() if k.startswith('radius_body_')]
            for i, r in enumerate(radius_body):
                self.input_args_fabrics["radius_body_" + str(i)][:FabricsArgumentSize.COLLISION_LINK_DIM] = np.array([r], dtype=np.float64)
                # data.append(np.array([r], dtype=np.float64))
                msg_type_counter += 1
        
        # radius obst
        if self.config["num_obstacles"] > 0: #TODO: potential error because sometimes its single float, sometimes np.array
            radius_obsts = [v for k, v in arg_dict.items() if k.startswith('radius_obst')]
            for i, r in enumerate(radius_obsts[0]): 
                self.input_args_fabrics["radius_obst_"+str(i)][:FabricsArgumentSize.OBSTACLE_DIM] =  np.array([r], dtype=np.float64)
                # data.append(np.array([r], dtype=np.float64))
                msg_type_counter += 1
        
        # weight goal
        if len(self.config["dim_goals"]) > 0:
            weight_goal = [v for k, v in arg_dict.items() if k.startswith('weight_goal_')]
            for i, w in enumerate(weight_goal):
                self.input_args_fabrics["weight_goal_"+str(i)][:FabricsArgumentSize.GOAL_WEIGTH_DIM] = np.array([w], dtype=np.float64)
                # data.append(np.array([w], dtype=np.float64))
                msg_type_counter += 1
        
        if len(self.config["dim_goals"]) > 0:
            x_goals = [v for k, v in arg_dict.items() if k.startswith('x_goal')]
            for i, goal in enumerate(x_goals):
                # data.append(np.array(goal, dtype=np.float64))
                self.input_args_fabrics["x_goal_"+str(i)] = np.asarray(goal, dtype=np.float64)
                msg_type_counter += 1

        # x_obst
        if self.config["num_obstacles"] > 0:
             x_obsts = [v for k, v in arg_dict.items() if k.startswith('x_obst')]
             for i, obst in enumerate(x_obsts[0]):  #TODO: potential error because sometimes its single float, sometimes np.array
                # data.append(np.array(obst, dtype=np.float64))
                self.input_args_fabrics["x_obst"+str(i)] = np.asarray(obst, dtype=np.float64)
                msg_type_counter += 1

        assert self.desired_msg_types == msg_type_counter, f"Desired arg length {self.desired_msg_types} is not the same as msg length {msg_type_counter}"
        # copy data
        data = []
        for key in self.input_args_fabrics:
            data.append(self.input_args_fabrics[key])

        return data