[tool.poetry]
name = "g3f_planner"
version = "0.1.0"
description = ""
authors = ["Tomas Merva", "Saray Bakker"]
readme = "README.md"
homepage = "https://github.com/TomasMerva/grasp_fabrics"
repository = "https://github.com/TomasMerva/grasp_fabrics"

[tool.poetry.dependencies]
python = ">=3.8, <3.10"
fabrics = "<0.9.6"
robotmodels = { git = "https://github.com/maxspahn/robotmodels.git"}
urdfenvs = "^0.9.13"
osqp = ">=0.6.5"
texttable = "^1.7.0"
latextable = "^1.0.1"
tqdm = "^4.66.5"
casadi = "3.6.6"
spatial-casadi = "1.1.0"
pytest = "6.2.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
