[tool.poetry]
name = "fabrics_rollouts"
version = "0.2.0"
description = ""
authors = ["Tomas Merva"]
readme = "README.md"
homepage = "https://github.com/TomasMerva/grasp_fabrics"
repository = "https://github.com/TomasMerva/grasp_fabrics"

[tool.poetry.dependencies]
python = ">=3.8, <3.10"
fabrics = "<0.9.6"
robotmodels = { git = "https://github.com/maxspahn/robotmodels.git"}
urdfenvs = "^0.9.13"
pytorch_kinematics = "^0.6.1"
grasp_planning =">=0.6"
osqp = ">=0.6.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
