# -*- coding: utf-8 -*-
from setuptools import setup

packages = \
['fabrics_rollouts',
 'fabrics_rollouts.scripts.constraints',
 'fabrics_rollouts.scripts.cpp_bridge',
 'fabrics_rollouts.scripts.rollout',
 'fabrics_rollouts.scripts.solver',
 'fabrics_rollouts.scripts.utils']

package_data = \
{'': ['*'], 'fabrics_rollouts': ['src/*']}

install_requires = \
['fabrics<0.9.6',
 'grasp_planning>=0.6',
 'osqp>=0.6.5',
 'pytorch_kinematics>=0.6.1,<0.7.0',
 'robotmodels @ git+https://github.com/maxspahn/robotmodels.git',
 'urdfenvs>=0.9.13,<0.10.0']

setup_kwargs = {
    'name': 'fabrics_rollouts',
    'version': '0.3.0',
    'description': '',
    'long_description': '# grasp_fabrics\n\n\n## Requirements\n```bash\npoetry install\n```\n\n\n## Build\n1. Fabrics shared library (C++)\n```bash\ngit clone git@github.com:TomasMerva/grasp_fabrics.git\ncd grasp_fabrics && mkdir build\ncd build\ncmake ..\nmake\n```\n2. Fabrics Client (python)\n```bash\ncd grasp_fabrics\npoetry install\n```\n\n## Use\n1. Using autogenerated fabrics controller\n```bash\npython examples/rollouts/example_fabrics_driver.py\n```\n2. Using rollouts\n```bash\npython examples/rollouts/example_dinova_rollout.py\n```\n\n## Warnings\n1. If you generate a new fabrics controller, you need to rebuild shared library in the `build` folder.\n2. The autogenerated fabrics controller has to be in the `fabrics_rollouts/src/` folder.\n',
    'author': 'Tomas Merva',
    'author_email': 'None',
    'maintainer': 'None',
    'maintainer_email': 'None',
    'url': 'https://github.com/TomasMerva/grasp_fabrics',
    'packages': packages,
    'package_data': package_data,
    'install_requires': install_requires,
    'python_requires': '>=3.8,<3.10',
}


setup(**setup_kwargs)

