#!/usr/bin/python3
import os
import numpy as np
from forwardkinematics.urdfFks.generic_urdf_fk import GenericURDFFk
from fabrics.planner.parameterized_planner import ParameterizedFabricPlanner
import yaml
import shutil


def set_planner(robot_urdf_path: str, 
                config_dict: dict, 
                controller_file: str,
                degrees_of_freedom: int = 9):
    with open(robot_urdf_path, "r", encoding="utf-8") as file:
        urdf = file.read()
    forward_kinematics = GenericURDFFk(
        urdf,
        root_link="world",
        end_links=["arm_tool_frame", "arm_orientation_helper_link"],
    )

    # Slowing down mobile base with respect to the arm
    base_metric = np.eye(9) * 0.3
    base_metric[0, 0] = 2
    base_metric[1, 1] = 2
    base_metric[2, 2] = 2
    base_energy = f"ca.dot(ca.mtimes(np.array({base_metric.tolist()}), xdot), xdot)"

    planner = ParameterizedFabricPlanner(
        degrees_of_freedom,
        forward_kinematics,
        base_energy=base_energy
    )

    planner.load_fabrics_configuration(config_dict['fabrics'])
    planner.load_problem_configuration(config_dict['problem'])
    planner.concretize()
    planner.export_as_c(controller_file)
    
    # Move to src folder
    current_script_dir = os.path.dirname(os.path.abspath(__file__))
    CONTROLLER_FOLDER_NEW = os.path.normpath(os.path.join(current_script_dir, "../../g3f_planner/src/", controller_file))
    print("Controller exported to:", CONTROLLER_FOLDER_NEW)
    shutil.move(controller_file, CONTROLLER_FOLDER_NEW)
    return planner



    

if __name__ == "__main__":
    ROBOT = "/dinova/dinova.urdf"
    FABRICS_CONFIG_FILE = "dinova_config_g3f_5obst.yaml"
    AUTOGENERATED_CONTROLLER_FILE = "fabrics_controller_5obst.cpp"
    N_DOF = 9

    # Handle files
    current_script_dir = os.path.dirname(os.path.abspath(__file__))
    urdf_folder = os.path.normpath(os.path.join(current_script_dir, '..', 'urdfs'))
    ROBOT_URDF_FILE = urdf_folder + ROBOT
    config_file_path = os.path.normpath(os.path.join(current_script_dir, '../..', 'config', FABRICS_CONFIG_FILE))
    with open(config_file_path, 'r') as config_file:
        CONFIG = yaml.safe_load(config_file)


    # Generate planner
    planner_dinova = set_planner(robot_urdf_path = ROBOT_URDF_FILE,
                                 config_dict = CONFIG,
                                 controller_file=AUTOGENERATED_CONTROLLER_FILE,
                                 degrees_of_freedom = N_DOF)