problem:
  environment:
    number_cuboids:
      dynamic: 0
      static: 0
    number_planes: 0
    number_spheres:
      dynamic: 0
      static: 10
    obstacle_definition:
      obstacle1: # table1
        type: sphere
        position: [0.0, 0.0, -0.05]
        radius: 0.25
      obstacle2: # table1 top
        type: sphere
        position: [0.0, 0.0, 0.3]
        radius: 0.1
      obstacle3:
        type: sphere
        position: [0.25, 1.5, 0.15]
        radius: 0.3
      obstacle4:
        type: sphere
        position: [-0.25, 1.5, 0.15]
        radius: 0.3
      obstacle5:
        type: sphere
        position: [-10.65, 1.75, 0.15]
        radius: 0.3
      obstacle6:
        type: sphere
        position: [10.65, 1.75, 0.15]
        radius: 0.3
      obstacle7: #side1
        type: sphere
        position: [10.9, 2.25, 0.15]
        radius: 0.3
      obstacle8: #side2
        type: sphere
        position: [-10.9, 2.25, 0.15]
        radius: 0.3
      obstacle9: 
        type: sphere
        position: [-10.3, -0.3, 0.3]
        radius: 0.25
      obstacle10: 
        type: sphere
        position: [-10.3, -0.3, 0.3]
        radius: 0.1
  goal:
    goal_definition:
      subgoal0:
        weight: 1.0
        is_primary_goal: True
        indices: [0, 1, 2]
        parent_link: base_link
        child_link: arm_tool_frame
        desired_position: [-0.06,  -0.9, 0.35]
        epsilon: 0.05
        type: staticSubGoal
      subgoal1:
        weight: 5.0
        is_primary_goal: False
        indices: [0, 1, 2]
        parent_link: arm_dummy_link
        child_link: arm_tool_frame
        desired_position: [0, -1, 0.5]
        epsilon: 0.03
        type: staticSubGoal
      subgoal2:
        weight: 5.0
        is_primary_goal: False
        indices: [0, 1, 2]
        parent_link: arm_dummy_link
        child_link: arm_orientation_helper_link
        desired_position: [0, -1, 0.5]
        epsilon: 0.03
        type: staticSubGoal
      subgoal3:
        weight: 1.0
        is_primary_goal: False
        indices: [2]
        desired_position: [0.]
        epsilon: 0.015
        type: staticJointSpaceSubGoal
  joint_limits:
    lower_limits:
    - -10
    - -10
    - -10
    - -2.6896
    - -1.7628
    - -2.6197
    - -2.6002
    - -2.5302
    - -2.6002
    upper_limits:
    - 10
    - 10
    - 10
    - 2.6896
    - 0.70
    - 2.6197
    - 2.6002
    - 2.5302
    - 2.6002
    velocity:
    - 0.5
    - 0.5
    - 0.5
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
  robot_representation:
    collision_links:
      chassis_link:
        sphere:
          radius: 0.55
      arm_upper_wrist_link:
        sphere:
          radius: 0.2
    self_collision_pairs: {}
fabrics:
  limit_geometry: -0.1 / (x ** 1) * xdot ** 2 #-1.0 / (x ** 1) * xdot ** 2
  limit_finsler: 1.0/(x**2) * xdot**2
  collision_geometry: -0.2 / (x ** 1) * xdot ** 2 #-0.2 / (x ** 1) * xdot ** 2
  collision_finsler:  0.2/(x**2) * xdot**2 #0.2/(x**2) * (-0.5 * (ca.sign(xdot) - 1)) * xdot ** 2
  geometry_plane_constraint: -0.2 / (x ** 1) *  xdot ** 2
  finsler_plane_constraint: 0.2/(x**2) * xdot**2
gomp:
  n_waypoints : 10
  collision_links : ["chassis_link", "arm_upper_wrist_link"]
  collision_link_radius : [0.65, 0.15]
  rollout_dt : 0.05
  rollout_timesteps : 500
  rollout_tolerance : 0.1
  alpha_filter: 0.7
  initial_grasp_roll_deg : 90
  verbose: False
  n_optim_steps : 5
  fabrics_lib : "libfabrics_controller_10obst.so"